名前と点数を二人分入力し、点数が大きい方の名前を表示する｡
RyoImakia/kadai_c pull request #6
Opened 2017-11-27 07:05 UTC by RyoImakia

https://docs.google.com/spreadsheets/d/1Nl0LWyEksZ3kk-zj-UWr-ergBKcNK2FCuUHtJJJd5js/edit#gid=0&range=D10

2017-11-27 08:13 UTC, h2-kinoshita commented on A_5.c
> +	typedef struct{
インデント合わせましょう。

2017-11-27 08:14 UTC, h2-kinoshita commented on A_5.c
> +	}hyuman;
できればローマ字は避ける。 `human`

2017-11-27 08:21 UTC, h2-kinoshita requested changes

2017-11-27 08:21 UTC, h2-kinoshita commented on A_5.c
> +	if(kino.point > kuno.point){
A は Bである Or BはAであるって条件を、２つ入れ替えて書くのはあまりよくないかも。
この場合特殊なのは、引き分けの場合なので、

```
if (A.point == B.point) {
    printf(引き分け)
    return 0
} else if (A.point > B.point) {
    printf(Aのかち)
    return 0
} else {
    printf(Bのかち)
    return 0
}
```

の方が個人的に可読性はよい。

2017-11-27 08:24 UTC, RyoImakia commented on A_5.c
> +	typedef struct{
これで正解と思ってました。なおします。

2017-11-27 08:25 UTC, ysmra commented on A_5.c
>  	char kanma[] = ",";
カンマも英語表記でね（comma）
その上のセミコロンの前にスペースついてるのも気になる。

2017-11-27 08:25 UTC, ysmra commented on A_5.c
>  	kuno.point = atoi(kunoCp);
入力された文字列から構造体を作る処理が２つ続いてるので関数にしてみよう。

2017-11-27 08:26 UTC, RyoImakia commented on A_5.c
> +	if(kino.point > kuno.point){
一般的にこっちなんですか？
直します。

2017-11-27 08:30 UTC, h2-kinoshita commented on A_5.c
> +	if(kino.point > kuno.point){
基本的に `A はB であるか否か` であれば、その `否か` 　に当たる条件式は書かなくても意味が通じるので、書かないって感じかな。

リーダブルコード読んでる人だったらこう書くかもね。

2017-11-28 01:42 UTC, ysmra commented on A_5.c
> +}
kinoとkunoで関数を分ける必要あるかな？
あと、返り値が特にないのならvoidでOK
`void HogeHoge()`

2017-11-28 03:06 UTC, RyoImakia commented on A_5.c
> +}
訂正します！

2017-11-28 03:21 UTC, ysmra commented on A_5.c
> +	ParserArray(&kuno, &kino, &kunoArray, &kinoArray);
ちょっと関数のイメージと違うかな。。結局関数の中に同じ一連の処理がならんでる。
呼び出し側を下のような感じで、同じ処理に通すようにできないかな？
`
ParserArray(&kuno, &kunoArray);
ParserArray(&kino, &kinoArray);
`

2017-11-28 03:26 UTC, ytogawa commented on A_5.c
> +}man;
構造体の命名規約ってあったっけ。
なければ木下さんに作ってもらいましょう。
個人的にはUpper Camel Caseかな。

2017-11-28 03:26 UTC, ytogawa commented on A_5.c
> +void ParserArray(man *tempKuno, man *tempKino , char *kunoArray, char *kinoArray){
`ParserArray`こういう名前の付け方だったら動詞にしましょう。

2017-11-28 03:26 UTC, ytogawa commented on A_5.c
> +void ParserArray(man *tempKuno, man *tempKino , char *kunoArray, char *kinoArray){
`tempKuno`, `tempKino` 何がtempってことは一時的に使うもののはずで、この用途に適した名前ではないですね。

2017-11-28 03:26 UTC, ytogawa commented on A_5.c
> +void ParserArray(man *tempKuno, man *tempKino , char *kunoArray, char *kinoArray){
`kunoArray`, `kinoArray` 配列は型であって、名前としては適切ではない気がする。

2017-11-28 03:26 UTC, ytogawa commented on A_5.c
> +void ParserArray(man *tempKuno, man *tempKino , char *kunoArray, char *kinoArray){
関数が大きいです。
少なくとも入力と出力は1つずつにしないとだめ。

2017-11-28 03:26 UTC, ytogawa commented on A_5.c
> +	fgets(kinoArray, sizeof(kinoArray), stdin);
どっちかと言うと、関数化するかは別として、 表示->入力->パース がワンセットの方が綺麗だと思う。
その方が、たとえばもう一人追加とかになった場合に対処しやすい。

2017-11-28 03:26 UTC, ytogawa commented on A_5.c
> +	if(kino.point == kuno.point){
せっかくだから、ここも関数化しようか。

2017-11-28 06:26 UTC, ytogawa commented on A_5.c
> +	Man kino, kuno = {{'\0'}, 0};
ここ問題あるけど何かわかる？

2017-11-28 06:26 UTC, ytogawa commented on A_5.c
> +void CaseExcerpt(Man *proxyStructure, char *proxyCase){
メソッド名、引数名それぞれなんでこの名前にしたのか説明たのむ。

2017-11-28 06:26 UTC, ytogawa commented on A_5.c
> +	char comma[] = ",";
定数にしよう。

2017-11-28 06:26 UTC, ytogawa commented on A_5.c
> +	int caseSize;
この辺りの変数名もなぜこの名前にしたのか説明してみてほしい。

2017-11-28 06:26 UTC, ytogawa commented on A_5.c
> +	if(kino.point == kuno.point){
ここを関数化しなかった理由はなんでしょうか。

2017-11-28 06:28 UTC, RyoImakia commented on A_5.c
> +	if(kino.point == kuno.point){
うまくいかず、期限が今日までだからです。
時間があるときにします。

2017-11-28 06:28 UTC, RyoImakia commented on A_5.c
> +	Man kino, kuno = {{'\0'}, 0};
初期化が一方だけだからですか？

2017-11-28 06:32 UTC, RyoImakia commented on A_5.c
> +void CaseExcerpt(Man *proxyStructure, char *proxyCase){
入れ物+抜粋でCaseExcerpt
代理+構造体でproxyStructure
代理+入れ物でproxyCase
にしました。

2017-11-28 06:33 UTC, RyoImakia commented on A_5.c
> +	int caseSize;
commaPosition　=カンマの位置
caseCopy　=一度コピーする入れ物
caseSize　=入れ物の大きさ
です。

2017-11-28 06:54 UTC, ytogawa commented on A_5.c
> +void CaseExcerpt(Man *proxyStructure, char *proxyCase){
> 入れ物+抜粋でCaseExcerpt
入れ物を抜粋する関数って意味がよくわからないです

> 代理+構造体でproxyStructure
> 代理+入れ物でproxyCase
なんの代理ですか。
構造体は型であって、名前につけるものではないです。
入れ物は抽象的すぎる。

2017-11-28 07:01 UTC, ytogawa reviewed
コメント返し。

2017-11-28 07:01 UTC, ytogawa commented on A_5.c
> +	int caseSize;
> カンマの位置

これはOK

> 一度コピーする入れ物

意味がよくわからないです。

> 入れ物の大きさ

前のコメントの通り入れ物は抽象的すぎます。

2017-11-28 07:01 UTC, ytogawa commented on A_5.c
> +	Man kino, kuno = {{'\0'}, 0};
yes。修正してください。
変数の定義をカンマで区切る場合、初期化や修飾子等々がどの変数に対応しているのか理解していない場合は、2行に分けるのが無難です。

2017-11-28 07:01 UTC, ytogawa commented on A_5.c
> +	if(kino.point == kuno.point){
なるほど、承知しました。

2017-11-29 01:57 UTC, ytogawa commented on A_5.c
> +void ToPullOutString(Man *man, char *String){
動詞は`parse`か`deserialize`辺りが適切かと。

2017-11-29 01:57 UTC, ytogawa commented on A_5.c
> +void ToPullOutString(Man *man, char *String){
`Man *man` こいつが何を表しているかというと、処理の結果なので、`man`ではなく`result`等が適切かと。

2017-11-29 01:57 UTC, ytogawa commented on A_5.c
> +void ToPullOutString(Man *man, char *String){
`char *String` 先頭が大文字になってるのと、stringは抽象的すぎる。

2017-11-29 01:57 UTC, ytogawa commented on A_5.c
> +	int StringSize;
この↑の2変数も先頭大文字。
あともういっかい名前考えてみて。

2017-11-29 01:57 UTC, ytogawa commented on A_5.c
> +	StringSize = sizeof(String) / sizeof(String[0]);
`String`は`char *`なので、これだと要素数は取得できません。
課題が4文字なので、たまたま動いてるだけで、ロジックとしては誤りかと。

2017-11-29 01:57 UTC, ytogawa commented on A_5.c
> +void ToPullOutString(Man *man, char *String){
OUTパラメータは引数の末尾にあるケースが多いので、末尾にしましょう。

2017-11-29 06:45 UTC, ytogawa reviewed
なんか警告出てるので対応してください。

```
bash-3.2$ gcc A_5.c                                                                                                                                                                                                                           
A_5.c:18:18: warning: implicitly declaring library function 'strstr' with type 'char *(const char *, const char *)' [-Wimplicit-function-declaration]                                                                                         
        commaPosition = strstr(inputString, comma);                                                                                                                                                                                           
                        ^                                                                                                                                                                                                                     
A_5.c:18:18: note: include the header <string.h> or explicitly provide a declaration for 'strstr'                                                                                                                                             
A_5.c:21:2: warning: implicitly declaring library function 'strncpy' with type 'char *(char *, const char *, unsigned long)' [-Wimplicit-function-declaration]                                                                                
        strncpy(tensu, commaPosition + commaAndBlankSkip, 1);                                                                                                                                                                                 
        ^                                                                                                                                                                                                                                     
A_5.c:21:2: note: include the header <string.h> or explicitly provide a declaration for 'strncpy'                                                                                                                                             
A_5.c:45:15: warning: incompatible pointer types passing 'char (*)[10]' to parameter of type 'char *' [-Wincompatible-pointer-types]                                                                                                          
        ParserString(&inputStringKino, &kino);                                                                                                                                                                                                
                     ^~~~~~~~~~~~~~~~                                                                                                                                                                                                         
A_5.c:11:25: note: passing argument to parameter 'inputString' here                                                                                                                                                                           
void ParserString(char *inputString, Man *result){                                                                                                                                                                                            
                        ^                                                                                                                                                                                                                     
A_5.c:52:15: warning: incompatible pointer types passing 'char (*)[10]' to parameter of type 'char *' [-Wincompatible-pointer-types]                                                                                                          
        ParserString(&inputStringKuno, &kuno);                                                                                                                                                                                                
                     ^~~~~~~~~~~~~~~~                                                                                                                                                                                                         
A_5.c:11:25: note: passing argument to parameter 'inputString' here                                                                                                                                                                           
void ParserString(char *inputString, Man *result){                                                                                                                                                                                            
                        ^                                                                                                                                                                                                                     
4 warnings generated.                                                                                                                                                                                                                         
```

2017-11-29 10:28 UTC, h2-kinoshita commented
警告の理由を正しく説明できたら、通します。

2017-11-30 01:56 UTC, h-kinocoboy approved these changes
これもスペルミスや変数名・関数名の英語が変なところ(だいぶ指摘あったので治ってますが）あるので、ちゃんと英語勉強するようにー。

マージしていいよ。

2017-11-30 01:58 UTC, merged